package: netplan-generator

essential:
  - netplan-generator_copyright

slices:
  bins:
    essential:
      - libc6_libs
      - libglib2.0-0t64_libs
      - libnetplan1_libs
      - systemd_bins
    contents:
      /usr/libexec/netplan/generate:
      /usr/lib/systemd/system-generators/netplan:

  # the generator needs the folder and thus carry
  # a placeholder file, it will be removed and a
  # symlink to /usr/libexec/netplan/generate will
  # be created in this folder
  placeholder:
    contents:
      /usr/lib/netplan/PLACEHOLDER:

  copyright:
    contents:
      /usr/share/doc/netplan-generator/copyright:
